#!/usr/bin/env node
// Tier-1 leading indicator: VERIFIED CATCHES ON NAMED RECORDS, PER WEEK.
//
// Approved 2026-08-12, built 2026-08-13. It exists because G-1 has no gradient — the
// north-star count sat at 0 for 21 days and then jumped to 1, which tells you nothing
// on any of the days in between. This answers the one question that count cannot:
// IS THE ADOPTED SURFACE STILL ALIVE ENOUGH TO BE WORTH STEWARDING? A month of zeros
// is the signal to adopt a SECOND surface, not to try harder on this one.
//
// Derived from git history, never hand-maintained — same reason README's state block is
// generated. A figure a human retypes weekly is a figure that goes stale between retypes.
//
// WHAT COUNTS AS A CATCH: a GENERATED pin whose `expect` string CHANGED in a commit.
// That is not a proxy for record movement, it IS record movement — generated pins are
// rewritten wholesale by extract-pins.mjs from the mirror, so the only way one changes
// is that its bounds-table row moved upstream. The distinction falls out for free and
// matches the ledger's own history:
//   50c8096 (2026-07-28, editorial drift — dead cross-link + a missing `C` in LaTeX)
//     never touched claims.json at all: pins regenerated byte-identical. Zero catches,
//     correctly, even though the mirror really did drift and the alarm really did fire.
//   da17be3 (2026-08-02, "first pure record movement") moved exactly three.
//
// Deliberately NOT counted:
//   - HAND claims (C-1…C-11). Their `expect` is hand-edited for reasons other than a
//     record moving — re-anchoring to a different pinned string, for one — so counting
//     them would inflate the figure with our own editing.
//   - Pins ADDED or REMOVED. Upstream adding a constant (86a, 2026-07-28) grows the
//     ledger; it is not a record we caught moving. Our own instrument work (the 216-pin
//     extension, the A-11 negative pins) is likewise not a catch.
//
// Asserts nothing mathematical and renders no verdict — an indicator, like
// traffic-snapshot.mjs and gap-table.mjs, NOT an alarm. It never fails a build.

import { execFileSync } from "node:child_process";
import assert from "node:assert/strict";

const CLAIMS = "ledger/claims.json";

// stderr ignored: `show` probes a parent that legitimately predates the file.
const git = (...args) =>
  execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 << 20, stdio: ["ignore", "pipe", "ignore"] });

// Generated pins only, keyed id -> expected string. Tolerates a missing/!JSON blob
// (the commit before the file existed) by reporting nothing pinned yet.
export function generatedPins(blob) {
  const out = new Map();
  if (!blob) return out;
  let claims;
  try {
    claims = JSON.parse(blob);
  } catch {
    return out;
  }
  for (const c of claims) if (c && c.generated === true) out.set(c.id, c.expect);
  return out;
}

// The whole judgment of this script, isolated so the self-test can exercise it:
// present in BOTH sides with a DIFFERENT expected string. Added/removed/unchanged
// are all silent.
export function movedPins(prevBlob, nextBlob) {
  const prev = generatedPins(prevBlob);
  const next = generatedPins(nextBlob);
  const moved = [];
  for (const [id, expect] of next) {
    if (prev.has(id) && prev.get(id) !== expect) moved.push(id);
  }
  return moved.sort();
}

// Monday-anchored ISO week label, e.g. "2026-08-10" for the week of 10-16 Aug.
function weekOf(isoDate) {
  const d = new Date(`${isoDate}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7));
  return d.toISOString().slice(0, 10);
}

function show(ref) {
  try {
    return git("show", `${ref}:${CLAIMS}`);
  } catch {
    return null; // the file did not exist at that ref
  }
}

function history() {
  const log = git("log", "--format=%H %as", "--", CLAIMS).trim();
  if (!log) return [];
  return log
    .split("\n")
    .map((line) => {
      const [sha, date] = line.split(" ");
      const moved = movedPins(show(`${sha}~1`), show(sha));
      return { sha: sha.slice(0, 7), date, week: weekOf(date), moved };
    })
    .reverse();
}

if (process.argv.includes("--selftest")) {
  const pin = (id, expect, generated = true) => ({ id, expect, generated });
  const blob = (...claims) => JSON.stringify(claims);

  const base = blob(pin("pin:10c:L", "| $5/3$ |"), pin("C-7", "0.380876", false));

  // FIRES: a generated pin's expected row changed = a record moved.
  assert.deepEqual(movedPins(base, blob(pin("pin:10c:L", "| $7/\\sqrt{17}$ |"), pin("C-7", "0.380876", false))), [
    "pin:10c:L",
  ]);

  // SILENT (the four ways a claims.json edit is NOT a catch) —
  // a detector that only ever fires passes the first assertion while proving nothing.
  assert.deepEqual(movedPins(base, base), [], "unchanged must be silent");
  assert.deepEqual(
    movedPins(base, blob(pin("pin:10c:L", "| $5/3$ |"), pin("pin:86a:U", "| $1.8216$ |"), pin("C-7", "0.380876", false))),
    [],
    "an ADDED pin (upstream added a constant) must be silent",
  );
  assert.deepEqual(movedPins(base, blob(pin("C-7", "0.380876", false))), [], "a REMOVED pin must be silent");
  assert.deepEqual(
    movedPins(base, blob(pin("pin:10c:L", "| $5/3$ |"), pin("C-7", "0.380868", false))),
    [],
    "a HAND claim changing must be silent — hand claims are hand-edited",
  );

  // The file not existing yet (first commit) must not throw or count.
  assert.deepEqual(movedPins(null, base), []);
  assert.deepEqual(movedPins("not json", base), []);

  assert.equal(weekOf("2026-08-13"), "2026-08-10");
  assert.equal(weekOf("2026-08-10"), "2026-08-10", "Monday belongs to its own week");
  assert.equal(weekOf("2026-08-09"), "2026-08-03", "Sunday belongs to the week before");

  console.log("catch-rate.test: PASS (fires on a moved generated pin; silent on unchanged, added, removed, hand-claim, and absent-file; week buckets Monday-anchored)");
  process.exit(0);
}

const commits = history();
const weeks = new Map();
for (const c of commits) {
  if (!weeks.has(c.week)) weeks.set(c.week, []);
  weeks.get(c.week).push(...c.moved);
}

const thisWeek = weekOf(new Date().toISOString().slice(0, 10));
if (!weeks.has(thisWeek)) weeks.set(thisWeek, []);
const ordered = [...weeks.entries()].sort((a, b) => a[0].localeCompare(b[0]));

// Self-describing on purpose (orchestrator feedback 2026-08-13): the figure is a CEILING on
// catches, and the header has to say so, because a reader who skips the caveat line will quote
// whatever the header called it. It counts listing-position MOVEMENTS, one of which is our own
// merged PR. The zero side is unaffected — a zero on an upper bound is a true zero — and the
// zero side is the only half the decision rule consumes.
console.log(`# Record-listing MOVEMENTS per week — a CEILING on catches, not a count of them — ${new Date().toISOString()}`);
for (const [week, moved] of ordered) {
  const distinct = [...new Set(moved)].sort();
  const label = week === thisWeek ? " (current, partial)" : "";
  // The headline is DISTINCT RECORDS, not movements. Upstream reworked one attribution
  // paragraph three times on 2026-08-12 and pin:2a:U moved on each push; counting that as
  // three would measure upstream's typing speed and read as productivity (CLAUDE.md names
  // this indicator as the thing that corrupts). The raw movement count stays visible so
  // the burst is not hidden either.
  const burst = moved.length > distinct.length ? ` (${moved.length} movements)` : "";
  console.log(
    `${week}  ${String(distinct.length).padStart(3)}${burst}${label}${distinct.length ? `  ${distinct.join(" ")}` : ""}`,
  );
}

let dryWeeks = 0;
for (let i = ordered.length - 1; i >= 0; i--) {
  if (ordered[i][1].length) break;
  dryWeeks++;
}
const total = ordered.reduce((n, [, moved]) => n + new Set(moved).size, 0);
// QUOTE THE PER-WEEK FIGURE, NEVER THIS TOTAL. The indicator is a rate; the running total
// answers no question we ask of it and only ever grows, so it reads as progress by construction.
console.log(
  `\n${total} movement(s) on distinct pins across ${ordered.length} week(s) — quote the PER-WEEK figure, never this total; ${dryWeeks} consecutive week(s) with none (the current week counts only once it is already dry).`,
);
console.log("A month of zeros is the signal to adopt a SECOND surface, not to try harder on this one.");
// Stated every run rather than filed in a doc nobody re-reads: this figure is an UPPER
// BOUND on records caught moving. Two known inflations, both real in the history above:
//   - A citation-key rename moves a pin without moving a bound. pin:15a:U (2026-08-11) is
//     one — five bibliography keys normalised, every bound value byte-identical. Parsing
//     the value out of the cell to separate them would need numeric judgment that symbolic
//     cells ($K_{DR}+10^{-26}$), negatives and O(.) asymptotics defeat, and would put an
//     unverified mathematical claim in our own ledger. The pin rule applies to the
//     indicator built on it: this asserts LISTING POSITION MOVED, never "a record moved".
//   - Our OWN merged PRs land as upstream movement. pin:15a:U is again the case — that was
//     PR #141 landing, not a catch. Not deducted, because git cannot see whose commit it was.
console.log("Upper bound: a citation-key rename moves a pin without moving a bound, and our own merged PRs land as upstream movement (both true of pin:15a:U).");
