#!/usr/bin/env node
// Tier-1 leading indicator: VERIFIED CATCHES ON NAMED RECORDS, PER WEEK.
//
// Approved 2026-08-12, built 2026-08-13. It exists because G-1 has no gradient — the
// north-star count sat at 0 for 21 days and then jumped to 1, which tells you nothing
// on any of the days in between. This answers the one question that count cannot:
// IS THE ADOPTED SURFACE STILL ALIVE ENOUGH TO BE WORTH STEWARDING? A month of zeros
// is the signal to adopt a SECOND surface, not to try harder on this one.
//
// AMENDED 2026-08-14 (orchestrator-approved): THE ZEROS DO NOT FIRE ALONE. Before
// concluding the surface is dry, read docs/findings/ over the same window. Rationale is
// 2026-08-14 itself: upstream ADDED constants/87a.md, this indicator correctly counted
// zero (an addition is not a movement, and its selftest asserts that silence), and the
// same cycle produced the lane's best output in weeks — a verified defect in that new
// page's record row, found by hand. The zeros measure drift DETECTION only. The lane's
// single external acknowledgement, G-1 = 1, came from manual error DETECTION this
// indicator is built not to see. A trigger that consumes only the zeros would therefore
// read "surface is dry" off an instrument that cannot see the work.
//   Dry means BOTH reads dry: no movements AND no findings in the window.
//   And the amendment tightens the EVIDENCE BAR only — adopting a second surface remains
//   a surfaced decision for David/the orchestrator, never self-approved on a firing rule.
//   Deliberately NOT built: a counter over docs/findings/. A number we can raise by
//   writing more files is inflatable exactly like a self-rating, which this lane refuses
//   for the same reason. A human reads the window; nothing counts it.
//
// Derived from git history, never hand-maintained — same reason README's state block is
// generated. A figure a human retypes weekly is a figure that goes stale between retypes.
//
// WHAT COUNTS AS A CATCH: a GENERATED pin whose `expect` string CHANGED in a commit.
// That is not a proxy for record movement, it IS record movement — generated pins are
// rewritten wholesale by extract-pins.mjs from the mirror, so the only way one changes
// is that its bounds-table row moved upstream. The distinction falls out for free and
// matches the ledger's own history:
//   50c8096 (2026-07-28, editorial drift — dead cross-link + a missing `C` in LaTeX)
//     never touched claims.json at all: pins regenerated byte-identical. Zero catches,
//     correctly, even though the mirror really did drift and the alarm really did fire.
//   da17be3 (2026-08-02, "first pure record movement") moved exactly three.
//
// Deliberately NOT counted:
//   - HAND claims (C-1…C-11). Their `expect` is hand-edited for reasons other than a
//     record moving — re-anchoring to a different pinned string, for one — so counting
//     them would inflate the figure with our own editing.
//   - Pins ADDED or REMOVED. Upstream adding a constant (86a, 2026-07-28) grows the
//     ledger; it is not a record we caught moving. Our own instrument work (the 216-pin
//     extension, the A-11 negative pins) is likewise not a catch.
//
// Asserts nothing mathematical and renders no verdict — an indicator, like
// traffic-snapshot.mjs and gap-table.mjs, NOT an alarm. It never fails a build.

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import assert from "node:assert/strict";

const CLAIMS = "ledger/claims.json";
const ITEMS = "continuity/items.json";

// --- the candidate-correction queue, companion to the movement rate (2026-08-17) --------------
//
// The movement figure above measures whether the adopted SURFACE is still alive. It says nothing
// about whether WE are still producing correction candidates — which is the input G-1 actually
// consumes, since G-1 counts externally-acknowledged corrections. The two can move in opposite
// directions and on 2026-08-17 they did: zero movements this week while one verified defect sat
// waiting on a gate. Reporting only the first reads "quiet week"; reporting both reads "we found
// something and cannot act on it", which is strictly truer and points at the real constraint.
//
// COUNTED FROM AN EXPLICIT FLAG, never inferred from titles. A trusted-print figure that guesses
// which items qualify will eventually print a wrong number, and this one prints next to a rate
// where a wrong number reads as productivity. Set `correctionCandidate: true` on an item only when
// a defect in a stewarded surface is VERIFIED by us and awaiting a gate or a send — not once its
// correction has gone out (that is downstream), and not for an announcement rather than a fix.
//
// Renders a COUNT and no verdict: no threshold, no decision rule, nothing for a build to fail on.
export function correctionQueue(itemsJson) {
  let parsed;
  try {
    parsed = JSON.parse(itemsJson);
  } catch {
    return null; // unreadable ledger — say so rather than print a confident 0
  }
  const rows = Array.isArray(parsed?.items) ? parsed.items : null;
  if (!rows) return null;
  const open = rows.filter((i) => i && i.correctionCandidate === true && i.status !== "closed");
  return { depth: open.length, ids: open.map((i) => i.id) };
}

// stderr ignored: `show` probes a parent that legitimately predates the file.
const git = (...args) =>
  execFileSync("git", args, { encoding: "utf8", maxBuffer: 64 << 20, stdio: ["ignore", "pipe", "ignore"] });

// Generated pins only, keyed id -> expected string. Tolerates a missing/!JSON blob
// (the commit before the file existed) by reporting nothing pinned yet.
export function generatedPins(blob) {
  const out = new Map();
  if (!blob) return out;
  let claims;
  try {
    claims = JSON.parse(blob);
  } catch {
    return out;
  }
  for (const c of claims) if (c && c.generated === true) out.set(c.id, c.expect);
  return out;
}

// The whole judgment of this script, isolated so the self-test can exercise it:
// present in BOTH sides with a DIFFERENT expected string. Added/removed/unchanged
// are all silent.
export function movedPins(prevBlob, nextBlob) {
  const prev = generatedPins(prevBlob);
  const next = generatedPins(nextBlob);
  const moved = [];
  for (const [id, expect] of next) {
    if (prev.has(id) && prev.get(id) !== expect) moved.push(id);
  }
  return moved.sort();
}

// Monday-anchored ISO week label, e.g. "2026-08-10" for the week of 10-16 Aug.
function weekOf(isoDate) {
  const d = new Date(`${isoDate}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7));
  return d.toISOString().slice(0, 10);
}

// A week in which nothing committed claims.json is a DRY week, not an absent one.
// Until 2026-08-15 the week map held only weeks that touched the file, which was wrong in
// the one direction that mattered: in a real drought NOTHING commits claims.json (the file
// is rewritten only by a snapshot, and a snapshot only happens on drift), so the quiet weeks
// never entered the map, the trailing walk in trailingDry() hit the last ACTIVE week
// immediately, and `dryWeeks` could never exceed 1. The rule this indicator carries — "a
// month of zeros is the signal to adopt a second surface" — was resting on a counter that
// could not count to four. Found by reading this script's own output on 2026-08-15: the
// table skipped the week of 2026-08-03 entirely rather than printing it as a zero.
export function fillDryWeeks(weeks, thisWeek) {
  const keys = [...weeks.keys()].sort();
  const last = keys.length ? keys[keys.length - 1] : thisWeek;
  // Fill to whichever is later. A future-dated key (author clock skew) would otherwise sit
  // beyond the fill target with a gap in front of it — F3 of the 2026-08-15 review.
  const end = last > thisWeek ? last : thisWeek;
  let w = keys.length ? keys[0] : thisWeek;
  while (w <= end) {
    if (!weeks.has(w)) weeks.set(w, []);
    const d = new Date(`${w}T00:00:00Z`);
    d.setUTCDate(d.getUTCDate() + 7);
    w = d.toISOString().slice(0, 10);
  }
  return weeks;
}

// Trailing COMPLETED dry weeks, newest first. Isolated so the self-test can exercise the
// counter the decision rule actually consumes, rather than the table a human reads.
//
// The current week is excluded, and that exclusion is the whole point (F1 of the 2026-08-15
// cross-family review). The printed table labels the newest row "(current, partial)", but the
// label is on the surface a HUMAN reads while the rule acts on this number — so counting the
// partial week would fire "a month of zeros" up to six days early, on the Monday a drought had
// completed only three weeks. A month is four COMPLETED weeks. Weeks dated after the current
// one are excluded for the same reason and because they cannot be complete either.
//
// A movement still breaks the streak wherever it lands, current week included: if the surface
// moved this week it is not dry, whatever the completed-week count would otherwise say.
export function trailingDry(ordered, currentWeek) {
  let n = 0;
  for (let i = ordered.length - 1; i >= 0; i--) {
    const [week, moved] = ordered[i];
    if (moved.length) break;
    if (week >= currentWeek) continue;
    n++;
  }
  return n;
}

// git's %as is the author-LOCAL date, so "today" has to be the local calendar date as well.
// A UTC "today" buckets a Sunday-evening commit in a negative-offset zone into the week before
// the one "now" lands in, and the movement reads as an immediate dry week — F2 of the
// 2026-08-15 review. One zone on both sides of the comparison.
function localToday() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function show(ref) {
  try {
    return git("show", `${ref}:${CLAIMS}`);
  } catch {
    return null; // the file did not exist at that ref
  }
}

function history() {
  const log = git("log", "--format=%H %as", "--", CLAIMS).trim();
  if (!log) return [];
  return log
    .split("\n")
    .map((line) => {
      const [sha, date] = line.split(" ");
      const moved = movedPins(show(`${sha}~1`), show(sha));
      return { sha: sha.slice(0, 7), date, week: weekOf(date), moved };
    })
    .reverse();
}

if (process.argv.includes("--selftest")) {
  const pin = (id, expect, generated = true) => ({ id, expect, generated });
  const blob = (...claims) => JSON.stringify(claims);

  const base = blob(pin("pin:10c:L", "| $5/3$ |"), pin("C-7", "0.380876", false));

  // FIRES: a generated pin's expected row changed = a record moved.
  assert.deepEqual(movedPins(base, blob(pin("pin:10c:L", "| $7/\\sqrt{17}$ |"), pin("C-7", "0.380876", false))), [
    "pin:10c:L",
  ]);

  // SILENT (the four ways a claims.json edit is NOT a catch) —
  // a detector that only ever fires passes the first assertion while proving nothing.
  assert.deepEqual(movedPins(base, base), [], "unchanged must be silent");
  assert.deepEqual(
    movedPins(base, blob(pin("pin:10c:L", "| $5/3$ |"), pin("pin:86a:U", "| $1.8216$ |"), pin("C-7", "0.380876", false))),
    [],
    "an ADDED pin (upstream added a constant) must be silent",
  );
  assert.deepEqual(movedPins(base, blob(pin("C-7", "0.380876", false))), [], "a REMOVED pin must be silent");
  assert.deepEqual(
    movedPins(base, blob(pin("pin:10c:L", "| $5/3$ |"), pin("C-7", "0.380868", false))),
    [],
    "a HAND claim changing must be silent — hand claims are hand-edited",
  );

  // The file not existing yet (first commit) must not throw or count.
  assert.deepEqual(movedPins(null, base), []);
  assert.deepEqual(movedPins("not json", base), []);

  // --- candidate-correction queue: BOTH answers, on fixtures (KP-78) -----------------------
  const itemsBlob = (...rows) => JSON.stringify({ project: "x", items: rows });
  // FIRES: an open, flagged item is counted, and its id is named.
  assert.deepEqual(
    correctionQueue(itemsBlob({ id: "A-16", status: "open", correctionCandidate: true })),
    { depth: 1, ids: ["A-16"] },
    "an open flagged item must be counted",
  );
  // SILENT, the three ways an item is NOT in the queue. A counter that counts everything is
  // as useless as one that counts nothing, and here it would overstate our own productivity.
  assert.deepEqual(
    correctionQueue(itemsBlob({ id: "A-16", status: "closed", correctionCandidate: true })),
    { depth: 0, ids: [] },
    "a CLOSED flagged item must not be counted",
  );
  assert.deepEqual(
    correctionQueue(itemsBlob({ id: "W-3", status: "open" })),
    { depth: 0, ids: [] },
    "an open UNflagged item must not be counted — the flag is opt-in, never inferred",
  );
  assert.deepEqual(
    correctionQueue(itemsBlob({ id: "A-15", status: "open", correctionCandidate: "yes" })),
    { depth: 0, ids: [] },
    "only a literal true counts — a truthy string must not slip in",
  );
  // An unreadable ledger must report UNREADABLE, not a confident zero. A zero from a dead read is
  // indistinguishable from a measured zero, and this figure sits beside a decision narrative.
  assert.equal(correctionQueue("not json"), null, "unparseable items.json must return null, not 0");
  assert.equal(correctionQueue("{}"), null, "a JSON blob with no items array must return null, not 0");
  assert.equal(correctionQueue('{"items":"nope"}'), null, "a non-array items field must return null, not 0");

  assert.equal(weekOf("2026-08-13"), "2026-08-10");
  assert.equal(weekOf("2026-08-10"), "2026-08-10", "Monday belongs to its own week");
  assert.equal(weekOf("2026-08-09"), "2026-08-03", "Sunday belongs to the week before");

  // FIRES: four COMPLETED weeks with no claims.json commit must read as four dry weeks.
  // Before fillDryWeeks existed this same input printed two rows and reported dryWeeks 1 —
  // the drought the decision rule consumes was the drought it could not see.
  const drought = [...fillDryWeeks(new Map([["2026-07-06", ["pin:x:U"]]]), "2026-08-10").entries()].sort();
  assert.deepEqual(drought.map(([w]) => w), [
    "2026-07-06", "2026-07-13", "2026-07-20", "2026-07-27", "2026-08-03", "2026-08-10",
  ]);
  assert.equal(trailingDry(drought, "2026-08-10"), 4, "four completed quiet weeks must read as four");

  // SILENT — the partial current week is NOT a dry week (F1, 2026-08-15 review). The same
  // history one week earlier has only THREE completed dry weeks behind it, and counting the
  // partial would fire the month-of-zeros rule six days early.
  const early = [...fillDryWeeks(new Map([["2026-07-06", ["pin:x:U"]]]), "2026-08-03").entries()].sort();
  assert.equal(trailingDry(early, "2026-08-03"), 3, "the current partial week must not be counted");

  // SILENT: an unbroken run of weeks gains nothing, and an active newest week is not dry.
  assert.equal(fillDryWeeks(new Map([["2026-08-03", []], ["2026-08-10", ["pin:x:U"]]]), "2026-08-10").size, 2);
  assert.equal(
    trailingDry([["2026-08-03", []], ["2026-08-10", ["pin:x:U"]]], "2026-08-10"),
    0,
    "a movement in the current week breaks the streak wherever the completed weeks stand",
  );

  // A future-dated key (author clock skew) gets no gap in front of it and is not counted (F3).
  const skewed = [...fillDryWeeks(new Map([["2026-08-03", ["pin:x:U"]], ["2026-08-24", []]]), "2026-08-10").entries()].sort();
  assert.deepEqual(skewed.map(([w]) => w), ["2026-08-03", "2026-08-10", "2026-08-17", "2026-08-24"]);
  assert.equal(trailingDry(skewed, "2026-08-10"), 0, "weeks at or after the current one are not completed");

  console.log("catch-rate.test: PASS (fires on a moved generated pin; silent on unchanged, added, removed, hand-claim, and absent-file; week buckets Monday-anchored; 4 completed dry weeks read as 4, the partial current week is excluded, a full run fills nothing, and a future-dated key neither gaps nor counts)");
  process.exit(0);
}

const commits = history();
const weeks = new Map();
for (const c of commits) {
  if (!weeks.has(c.week)) weeks.set(c.week, []);
  weeks.get(c.week).push(...c.moved);
}

const thisWeek = weekOf(localToday());
const ordered = [...fillDryWeeks(weeks, thisWeek).entries()].sort((a, b) => a[0].localeCompare(b[0]));

// Self-describing on purpose (orchestrator feedback 2026-08-13): the figure is a CEILING on
// catches, and the header has to say so, because a reader who skips the caveat line will quote
// whatever the header called it. It counts listing-position MOVEMENTS, one of which is our own
// merged PR. The zero side is unaffected — a zero on an upper bound is a true zero — and the
// zero side is the only half the decision rule consumes.
console.log(`# Record-listing MOVEMENTS per week — a CEILING on catches, not a count of them — ${new Date().toISOString()}`);
for (const [week, moved] of ordered) {
  const distinct = [...new Set(moved)].sort();
  const label = week === thisWeek ? " (current, partial)" : "";
  // The headline is DISTINCT RECORDS, not movements. Upstream reworked one attribution
  // paragraph three times on 2026-08-12 and pin:2a:U moved on each push; counting that as
  // three would measure upstream's typing speed and read as productivity (CLAUDE.md names
  // this indicator as the thing that corrupts). The raw movement count stays visible so
  // the burst is not hidden either.
  const burst = moved.length > distinct.length ? ` (${moved.length} movements)` : "";
  console.log(
    `${week}  ${String(distinct.length).padStart(3)}${burst}${label}${distinct.length ? `  ${distinct.join(" ")}` : ""}`,
  );
}

const dryWeeks = trailingDry(ordered, thisWeek);
const total = ordered.reduce((n, [, moved]) => n + new Set(moved).size, 0);
// QUOTE THE PER-WEEK FIGURE, NEVER THIS TOTAL. The indicator is a rate; the running total
// answers no question we ask of it and only ever grows, so it reads as progress by construction.
console.log(
  `\n${total} movement(s) on distinct pins across ${ordered.length} week(s) — quote the PER-WEEK figure, never this total; ${dryWeeks} COMPLETED consecutive week(s) with none — the current partial week is never counted, and a month is four.`,
);
console.log("A month of zeros is the signal to adopt a SECOND surface, not to try harder on this one.");
console.log(
  "The zeros do NOT fire that alone (amended 2026-08-14): read docs/findings/ over the same window first — dry means no movements AND no findings. This counts drift DETECTION only, and G-1's one acknowledgement came from manual error detection it cannot see. Adopting a second surface stays David's call, never self-approved.",
);
// Stated every run rather than filed in a doc nobody re-reads: this figure is an UPPER
// BOUND on records caught moving. Two known inflations, both real in the history above:
//   - A citation-key rename moves a pin without moving a bound. pin:15a:U (2026-08-11) is
//     one — five bibliography keys normalised, every bound value byte-identical. Parsing
//     the value out of the cell to separate them would need numeric judgment that symbolic
//     cells ($K_{DR}+10^{-26}$), negatives and O(.) asymptotics defeat, and would put an
//     unverified mathematical claim in our own ledger. The pin rule applies to the
//     indicator built on it: this asserts LISTING POSITION MOVED, never "a record moved".
//   - Our OWN merged PRs land as upstream movement. pin:15a:U is again the case — that was
//     PR #141 landing, not a catch. Not deducted, because git cannot see whose commit it was.
console.log("Upper bound: a citation-key rename moves a pin without moving a bound, and our own merged PRs land as upstream movement (both true of pin:15a:U).");

// Companion line: the movements figure is about the SURFACE, this is about US. Read together.
{
  let raw = null;
  try {
    raw = readFileSync(ITEMS, "utf8");
  } catch {
    /* fall through to the unreadable branch */
  }
  const q = raw === null ? null : correctionQueue(raw);
  if (q === null) {
    console.log(
      `\nCandidate-correction queue: UNREADABLE — could not parse ${ITEMS}. Not a zero; a zero here and a broken read are different facts and must not print the same.`,
    );
  } else {
    console.log(
      `\nCandidate-correction queue depth: ${q.depth}${q.ids.length ? `  (${q.ids.join(" ")})` : ""} — verified defects in a stewarded surface awaiting a gate or a send, counted from the explicit correctionCandidate flag in ${ITEMS}.`,
    );
    console.log(
      "Read this WITH the per-week figure, not instead of it: the rate says whether the surface is still moving, this says whether we are still finding things. A zero rate beside a non-zero queue is not a quiet week — it is work found and blocked.",
    );
  }
}
